spring:
  security:
    oauth2:
      client:
        registration: 
          google: 
            client-id: Google ID
            client-secret: Google Pass
            scope:
              - email
              - profile
